### ISSUE TITLE
Multiple forms on a single page

### ISSUE THREAD

**Issue by shammar13** [casperin/nod#111] opened 2015-08-26 14:46 UTC
Hi @casperin 

I have a use-case where I have multiple forms (all with the same fields) on the one page.

I've configured Nod's validation rules to use class selectors. I've set it up with one form, and it works perfectly. But if I duplicate that form, then only the first form validates correctly. The subsequent forms do not.

Essentially, the submit buttons are not being disabled and validation isn't being triggered on the other forms.

Is this related to issue #108?

This is what my validation looks like right now:
```js
var n = nod();

n.configure({
    submit: '.js-validate-submit',
    disableSubmit: true,
    delay: 250,
    errorClass: "error",
    errorMessageClass: 'error-message'
});

n.add([{
    selector: '.js-validate-name',
    validate: 'presence',
    errorMessage: 'Please enter your name',
    defaultStatus: 'invalid'
}, {
    selector: '.js-validate-surname',
    validate: 'presence',
    errorMessage: 'Please enter your surname',
    defaultStatus: 'invalid'
}, {
    selector: '.js-validate-phone-number',
    validate: 'presence',
    errorMessage: 'Please enter your phone number'
}, {
    selector: '.js-validate-email',
    validate: ['presence', 'email'],
    errorMessage: ['Please enter your email address', 'Email address is invalid']
}, {
    selector: '.js-validate-comments',
    validate: 'presence',
    errorMessage: 'Please enter suitable comments',
    defaultStatus: 'invalid'
}]);
```

**Comment by casperin** [comment] 2015-12-25 11:49
@shammar13, I am so sorry for not responding to this at all. Did you figure it out?

I have not looked at `nod` for a *long* time now, so it'll take me some time to get back into it and figure out what the problem is. I don't mind doing that, but if you've moved on long ago (which I suspect you have), then of course I'd rather spend my time with some of the other issues.

I'll close this ticket, but please do me the favour of reopening it if it's still a problem. Also, the code you provide is great, but a jsfiddle/jsbin/codepen is even better, since I can edit the code right there in the browser without having to reproduce the setup locally and hoping I get it right.

**Closed by casperin** 2015-12-25 11:49 UTC
